services:
  - type: web
    name: ayur-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
